from __future__ import annotations

FRED_TIMEOUT_SECONDS = 10
YAHOO_TIMEOUT_SECONDS = 15
ECOS_TIMEOUT_SECONDS = 20
FRED_SERIES = {
    "cpi": [
        {
            "series_id": "US_CPI_ALL",
            "fred_id": "CPIAUCSL",
            "country": "US",
            "name": "US CPI All Urban Consumers",
            "frequency": "M",
            "index_base": "1982-84=100",
        },
        {
            "series_id": "KOR_CPI_ALL",
            "fred_id": "KORCPIALLMINMEI",
            "country": "KR",
            "name": "Korea CPI All Items",
            "frequency": "M",
            "index_base": "2015=100",
        },
    ],
    "rates": [
        {
            "series_id": "US_FED_FUNDS",
            "fred_id": "FEDFUNDS",
            "country": "US",
            "name": "Federal Funds Effective Rate",
            "frequency": "M",
            "tenor": "overnight",
            "unit": "percent",
        },
        {
            "series_id": "US_TREASURY_2Y",
            "fred_id": "DGS2",
            "country": "US",
            "name": "US Treasury 2-Year Constant Maturity",
            "frequency": "D",
            "tenor": "2Y",
            "unit": "percent",
        },
        {
            "series_id": "US_TREASURY_10Y",
            "fred_id": "DGS10",
            "country": "US",
            "name": "US Treasury 10-Year Constant Maturity",
            "frequency": "D",
            "tenor": "10Y",
            "unit": "percent",
        },
        {
            "series_id": "US_TREASURY_30Y",
            "fred_id": "DGS30",
            "country": "US",
            "name": "US Treasury 30-Year Constant Maturity",
            "frequency": "D",
            "tenor": "30Y",
            "unit": "percent",
        },
        {
            "series_id": "KR_GOVT_10Y",
            "fred_id": "IRLTLT01KRM156N",
            "country": "KR",
            "name": "Korea 10-Year Government Bond Yield",
            "frequency": "M",
            "tenor": "10Y",
            "unit": "percent",
        },
        {
            "series_id": "JP_GOVT_10Y",
            "fred_id": "IRLTLT01JPM156N",
            "country": "JP",
            "name": "Japan 10-Year Government Bond Yield",
            "frequency": "M",
            "tenor": "10Y",
            "unit": "percent",
        },
        {
            "series_id": "DE_GOVT_10Y",
            "fred_id": "IRLTLT01DEM156N",
            "country": "DE",
            "name": "Germany 10-Year Government Bond Yield",
            "frequency": "M",
            "tenor": "10Y",
            "unit": "percent",
        },
        {
            "series_id": "FR_GOVT_10Y",
            "fred_id": "IRLTLT01FRM156N",
            "country": "FR",
            "name": "France 10-Year Government Bond Yield",
            "frequency": "M",
            "tenor": "10Y",
            "unit": "percent",
        },
        {
            "series_id": "GB_GOVT_10Y",
            "fred_id": "IRLTLT01GBM156N",
            "country": "GB",
            "name": "United Kingdom 10-Year Government Bond Yield",
            "frequency": "M",
            "tenor": "10Y",
            "unit": "percent",
        },
    ],
}
ECOS_RATE_SERIES = [
    {
        "series_id": "KR_BASE_RATE_ECOS",
        "stat_code": "722Y001",
        "cycle": "D",
        "items": ("0101000",),
        "country": "KR",
        "name": "Bank of Korea Base Rate",
        "frequency": "D",
        "tenor": "overnight",
        "unit": "percent",
    },
    {
        "series_id": "KR_CALL_RATE_ECOS",
        "stat_code": "817Y002",
        "cycle": "D",
        "items": ("010101000",),
        "country": "KR",
        "name": "Korea Call Rate 1-Day",
        "frequency": "D",
        "tenor": "overnight",
        "unit": "percent",
    },
    {
        "series_id": "KR_GOVT_2Y_ECOS",
        "stat_code": "817Y002",
        "cycle": "D",
        "items": ("010195000",),
        "country": "KR",
        "name": "Korea Treasury Bond 2-Year Yield",
        "frequency": "D",
        "tenor": "2Y",
        "unit": "percent",
    },
    {
        "series_id": "KR_GOVT_3Y_ECOS",
        "stat_code": "817Y002",
        "cycle": "D",
        "items": ("010200000",),
        "country": "KR",
        "name": "Korea Treasury Bond 3-Year Yield",
        "frequency": "D",
        "tenor": "3Y",
        "unit": "percent",
    },
    {
        "series_id": "KR_GOVT_5Y_ECOS",
        "stat_code": "817Y002",
        "cycle": "D",
        "items": ("010200001",),
        "country": "KR",
        "name": "Korea Treasury Bond 5-Year Yield",
        "frequency": "D",
        "tenor": "5Y",
        "unit": "percent",
    },
    {
        "series_id": "KR_GOVT_10Y_ECOS",
        "stat_code": "817Y002",
        "cycle": "D",
        "items": ("010210000",),
        "country": "KR",
        "name": "Korea Treasury Bond 10-Year Yield",
        "frequency": "D",
        "tenor": "10Y",
        "unit": "percent",
    },
    {
        "series_id": "KR_CORP_AA_3Y_ECOS",
        "stat_code": "817Y002",
        "cycle": "D",
        "items": ("010300000",),
        "country": "KR",
        "name": "Korea Corporate Bond AA- 3-Year Yield",
        "frequency": "D",
        "tenor": "3Y",
        "unit": "percent",
    },
    {
        "series_id": "KR_CD_91D_ECOS",
        "stat_code": "817Y002",
        "cycle": "D",
        "items": ("010502000",),
        "country": "KR",
        "name": "Korea CD 91-Day Yield",
        "frequency": "D",
        "tenor": "91D",
        "unit": "percent",
    },
    {
        "series_id": "KR_KOFR_ECOS",
        "stat_code": "817Y002",
        "cycle": "D",
        "items": ("010901000",),
        "country": "KR",
        "name": "Korea Overnight Financing Repo Rate",
        "frequency": "D",
        "tenor": "overnight",
        "unit": "percent",
    },
    {
        "series_id": "KR_BANK_MORTGAGE_RATE_ECOS",
        "stat_code": "121Y006",
        "cycle": "M",
        "items": ("BECBLA0302",),
        "country": "KR",
        "name": "Korea Bank Mortgage Loan Rate",
        "frequency": "M",
        "tenor": "loan",
        "unit": "percent",
    },
    {
        "series_id": "KR_BANK_CREDIT_LOAN_RATE_ECOS",
        "stat_code": "121Y006",
        "cycle": "M",
        "items": ("BECBLA03051",),
        "country": "KR",
        "name": "Korea Bank Unsecured Consumer Loan Rate",
        "frequency": "M",
        "tenor": "loan",
        "unit": "percent",
    },
]
ECOS_FX_SERIES = [
    {
        "series_id": "USD_KRW_ECOS",
        "stat_code": "731Y001",
        "cycle": "D",
        "items": ("0000001",),
        "base_currency": "USD",
        "quote_currency": "KRW",
    },
    {
        "series_id": "EUR_KRW_ECOS",
        "stat_code": "731Y001",
        "cycle": "D",
        "items": ("0000003",),
        "base_currency": "EUR",
        "quote_currency": "KRW",
    },
    {
        "series_id": "CNY_KRW_ECOS",
        "stat_code": "731Y001",
        "cycle": "D",
        "items": ("0000053",),
        "base_currency": "CNY",
        "quote_currency": "KRW",
    },
    {
        "series_id": "JPY100_KRW_ECOS",
        "stat_code": "731Y001",
        "cycle": "D",
        "items": ("0000002",),
        "base_currency": "JPY100",
        "quote_currency": "KRW",
    },
]
ECOS_CPI_SERIES = [
    {
        "series_id": "KR_CPI_ALL_ECOS",
        "stat_code": "901Y009",
        "cycle": "M",
        "items": ("0",),
        "country": "KR",
        "name": "Korea CPI All Items",
        "frequency": "M",
        "index_base": "2020=100",
    },
]
ECOS_ECONOMIC_SERIES = [
    {
        "series_id": "KR_REAL_GDP_SA_ECOS",
        "stat_code": "200Y108",
        "cycle": "Q",
        "items": ("10601",),
        "country": "KR",
        "name": "Korea Real GDP SA",
        "category": "growth",
        "frequency": "Q",
        "unit": "billions_krw",
    },
    {
        "series_id": "KR_NOMINAL_GDP_SA_ECOS",
        "stat_code": "200Y107",
        "cycle": "Q",
        "items": ("10601",),
        "country": "KR",
        "name": "Korea Nominal GDP SA",
        "category": "growth",
        "frequency": "Q",
        "unit": "billions_krw",
    },
    {
        "series_id": "KR_CURRENT_ACCOUNT_SA_ECOS",
        "stat_code": "301Y017",
        "cycle": "M",
        "items": ("SA000",),
        "country": "KR",
        "name": "Korea Current Account SA",
        "category": "external",
        "frequency": "M",
        "unit": "millions_usd",
    },
    {
        "series_id": "KR_UNEMPLOYMENT_RATE_SA_ECOS",
        "stat_code": "901Y027",
        "cycle": "M",
        "items": ("I61BC", "I28B"),
        "country": "KR",
        "name": "Korea Unemployment Rate SA",
        "category": "labor",
        "frequency": "M",
        "unit": "percent",
    },
    {
        "series_id": "KR_EMPLOYMENT_RATE_SA_ECOS",
        "stat_code": "901Y027",
        "cycle": "M",
        "items": ("I61E", "I28B"),
        "country": "KR",
        "name": "Korea Employment Rate SA",
        "category": "labor",
        "frequency": "M",
        "unit": "percent",
    },
    {
        "series_id": "KR_INDUSTRIAL_PRODUCTION_SA_ECOS",
        "stat_code": "901Y033",
        "cycle": "M",
        "items": ("A00", "2"),
        "country": "KR",
        "name": "Korea All-Industry Production Index SA",
        "category": "growth",
        "frequency": "M",
        "unit": "index_2020_100",
    },
    {
        "series_id": "KR_RETAIL_SALES_REAL_SA_ECOS",
        "stat_code": "901Y100",
        "cycle": "M",
        "items": ("G0", "T3"),
        "country": "KR",
        "name": "Korea Retail Sales Index SA",
        "category": "consumption",
        "frequency": "M",
        "unit": "index_2020_100",
    },
    {
        "series_id": "KR_UNSOLD_HOMES_ECOS",
        "stat_code": "901Y074",
        "cycle": "M",
        "items": ("I410A",),
        "country": "KR",
        "name": "Korea Unsold Homes",
        "category": "housing",
        "frequency": "M",
        "unit": "homes",
    },
    {
        "series_id": "KR_HOUSEHOLD_CREDIT_ECOS",
        "stat_code": "151Y001",
        "cycle": "Q",
        "items": ("1000000",),
        "country": "KR",
        "name": "Korea Household Credit",
        "category": "credit",
        "frequency": "Q",
        "unit": "billions_krw",
    },
    {
        "series_id": "KR_DEPOSIT_TAKER_HOUSEHOLD_LOANS_ECOS",
        "stat_code": "151Y002",
        "cycle": "M",
        "items": ("1110000",),
        "country": "KR",
        "name": "Korea Deposit-Taker Household Loans",
        "category": "credit",
        "frequency": "M",
        "unit": "billions_krw",
    },
    {
        "series_id": "KR_M2_SA_ECOS",
        "stat_code": "161Y005",
        "cycle": "M",
        "items": ("BBHS00",),
        "country": "KR",
        "name": "Korea M2 Average Balance SA",
        "category": "money",
        "frequency": "M",
        "unit": "billions_krw",
    },
]
FRED_ECONOMIC_SERIES = [
    {
        "series_id": "CPILFESL",
        "fred_id": "CPILFESL",
        "country": "US",
        "name": "US Core CPI",
        "category": "inflation",
        "frequency": "M",
        "unit": "index",
    },
    {
        "series_id": "PCEPI",
        "fred_id": "PCEPI",
        "country": "US",
        "name": "US PCE Price Index",
        "category": "inflation",
        "frequency": "M",
        "unit": "index",
    },
    {
        "series_id": "PCEPILFE",
        "fred_id": "PCEPILFE",
        "country": "US",
        "name": "US Core PCE Price Index",
        "category": "inflation",
        "frequency": "M",
        "unit": "index",
    },
    {
        "series_id": "PPIACO",
        "fred_id": "PPIACO",
        "country": "US",
        "name": "US Producer Price Index: All Commodities",
        "category": "inflation",
        "frequency": "M",
        "unit": "index",
    },
    {
        "series_id": "UNRATE",
        "fred_id": "UNRATE",
        "country": "US",
        "name": "US Unemployment Rate",
        "category": "labor",
        "frequency": "M",
        "unit": "percent",
    },
    {
        "series_id": "PAYEMS",
        "fred_id": "PAYEMS",
        "country": "US",
        "name": "US Total Nonfarm Payrolls",
        "category": "labor",
        "frequency": "M",
        "unit": "thousands",
    },
    {
        "series_id": "GDP",
        "fred_id": "GDP",
        "country": "US",
        "name": "US Gross Domestic Product",
        "category": "growth",
        "frequency": "Q",
        "unit": "billions_usd_saar",
    },
    {
        "series_id": "GDPC1",
        "fred_id": "GDPC1",
        "country": "US",
        "name": "US Real Gross Domestic Product",
        "category": "growth",
        "frequency": "Q",
        "unit": "billions_chained_2017_usd_saar",
    },
    {
        "series_id": "INDPRO",
        "fred_id": "INDPRO",
        "country": "US",
        "name": "US Industrial Production Index",
        "category": "growth",
        "frequency": "M",
        "unit": "index",
    },
    {
        "series_id": "RSAFS",
        "fred_id": "RSAFS",
        "country": "US",
        "name": "US Advance Retail Sales",
        "category": "consumption",
        "frequency": "M",
        "unit": "millions_usd",
    },
    {
        "series_id": "M2SL",
        "fred_id": "M2SL",
        "country": "US",
        "name": "US M2 Money Stock",
        "category": "money",
        "frequency": "M",
        "unit": "billions_usd",
    },
    {
        "series_id": "DGS2",
        "fred_id": "DGS2",
        "country": "US",
        "name": "US Treasury 2-Year Constant Maturity",
        "category": "rates",
        "frequency": "D",
        "unit": "percent",
    },
    {
        "series_id": "DGS5",
        "fred_id": "DGS5",
        "country": "US",
        "name": "US Treasury 5-Year Constant Maturity",
        "category": "rates",
        "frequency": "D",
        "unit": "percent",
    },
    {
        "series_id": "DGS30",
        "fred_id": "DGS30",
        "country": "US",
        "name": "US Treasury 30-Year Constant Maturity",
        "category": "rates",
        "frequency": "D",
        "unit": "percent",
    },
    {
        "series_id": "T10Y2Y",
        "fred_id": "T10Y2Y",
        "country": "US",
        "name": "US 10-Year Minus 2-Year Treasury Spread",
        "category": "rates",
        "frequency": "D",
        "unit": "percentage_points",
    },
    {
        "series_id": "T10Y3M",
        "fred_id": "T10Y3M",
        "country": "US",
        "name": "US 10-Year Minus 3-Month Treasury Spread",
        "category": "rates",
        "frequency": "D",
        "unit": "percentage_points",
    },
    {
        "series_id": "SOFR",
        "fred_id": "SOFR",
        "country": "US",
        "name": "Secured Overnight Financing Rate",
        "category": "rates",
        "frequency": "D",
        "unit": "percent",
    },
    {
        "series_id": "BAMLH0A0HYM2",
        "fred_id": "BAMLH0A0HYM2",
        "country": "US",
        "name": "US High Yield Option-Adjusted Spread",
        "category": "credit",
        "frequency": "D",
        "unit": "percent",
    },
    {
        "series_id": "MORTGAGE30US",
        "fred_id": "MORTGAGE30US",
        "country": "US",
        "name": "US 30-Year Fixed Mortgage Rate",
        "category": "housing",
        "frequency": "W",
        "unit": "percent",
    },
    {
        "series_id": "HOUST",
        "fred_id": "HOUST",
        "country": "US",
        "name": "US Housing Starts",
        "category": "housing",
        "frequency": "M",
        "unit": "thousands_saar",
    },
    {
        "series_id": "UMCSENT",
        "fred_id": "UMCSENT",
        "country": "US",
        "name": "University of Michigan Consumer Sentiment",
        "category": "sentiment",
        "frequency": "M",
        "unit": "index",
    },
    {
        "series_id": "DCOILWTICO",
        "fred_id": "DCOILWTICO",
        "country": "US",
        "name": "WTI Crude Oil Price",
        "category": "commodities",
        "frequency": "D",
        "unit": "usd_per_barrel",
    },
    {
        "series_id": "VIXCLS",
        "fred_id": "VIXCLS",
        "country": "US",
        "name": "CBOE Volatility Index: VIX",
        "category": "risk",
        "frequency": "D",
        "unit": "index",
    },
    {
        "series_id": "DTWEXBGS",
        "fred_id": "DTWEXBGS",
        "country": "US",
        "name": "Nominal Broad US Dollar Index",
        "category": "fx",
        "frequency": "D",
        "unit": "index",
    },
]
YAHOO_INDEX_SERIES = [
    {
        "series_id": "KOSPI",
        "symbol": "^KS11",
        "country": "KR",
        "name": "KOSPI Composite Index",
        "category": "equity_index",
        "currency": "KRW",
    },
    {
        "series_id": "KOSDAQ",
        "symbol": "^KQ11",
        "country": "KR",
        "name": "KOSDAQ Composite Index",
        "category": "equity_index",
        "currency": "KRW",
    },
    {
        "series_id": "SNP500",
        "symbol": "^GSPC",
        "country": "US",
        "name": "S&P 500 Index",
        "category": "equity_index",
        "currency": "USD",
    },
    {
        "series_id": "SP500",
        "symbol": "^GSPC",
        "country": "US",
        "name": "S&P 500 Index",
        "category": "equity_index",
        "currency": "USD",
    },
    {
        "series_id": "NASDAQ",
        "symbol": "^IXIC",
        "country": "US",
        "name": "NASDAQ Composite Index",
        "category": "equity_index",
        "currency": "USD",
    },
    {
        "series_id": "DOW_JONES",
        "symbol": "^DJI",
        "country": "US",
        "name": "Dow Jones Industrial Average",
        "category": "equity_index",
        "currency": "USD",
    },
    {
        "series_id": "NIKKEI_225",
        "symbol": "^N225",
        "country": "JP",
        "name": "Nikkei 225",
        "category": "equity_index",
        "currency": "JPY",
    },
    {
        "series_id": "HANG_SENG",
        "symbol": "^HSI",
        "country": "HK",
        "name": "Hang Seng Index",
        "category": "equity_index",
        "currency": "HKD",
    },
    {
        "series_id": "SSE_COMPOSITE",
        "symbol": "000001.SS",
        "country": "CN",
        "name": "Shanghai Composite Index",
        "category": "equity_index",
        "currency": "CNY",
    },
    {
        "series_id": "US_DOLLAR_INDEX",
        "symbol": "DX-Y.NYB",
        "country": "US",
        "name": "US Dollar Index",
        "category": "fx_index",
        "currency": "USD",
    },
]
YAHOO_RATE_SERIES = [
    {
        "series_id": "US_TREASURY_5Y_YAHOO",
        "symbol": "^FVX",
        "country": "US",
        "name": "US Treasury 5-Year Yield",
        "frequency": "D",
        "tenor": "5Y",
        "unit": "percent",
        "scale": "1",
    },
    {
        "series_id": "US_TREASURY_10Y_YAHOO",
        "symbol": "^TNX",
        "country": "US",
        "name": "US Treasury 10-Year Yield",
        "frequency": "D",
        "tenor": "10Y",
        "unit": "percent",
        "scale": "1",
    },
    {
        "series_id": "US_TREASURY_30Y_YAHOO",
        "symbol": "^TYX",
        "country": "US",
        "name": "US Treasury 30-Year Yield",
        "frequency": "D",
        "tenor": "30Y",
        "unit": "percent",
        "scale": "1",
    },
    {
        "series_id": "US_TREASURY_13W_YAHOO",
        "symbol": "^IRX",
        "country": "US",
        "name": "US Treasury 13-Week Yield",
        "frequency": "D",
        "tenor": "13W",
        "unit": "percent",
        "scale": "1",
    },
]
KRX_BOND_RATE_SERIES = [
    {
        "series_id": "KR_GOVT_3Y",
        "krx_kind": "국고채3년",
        "country": "KR",
        "name": "Korea Treasury Bond 3-Year Yield",
        "frequency": "D",
        "tenor": "3Y",
        "unit": "percent",
    },
    {
        "series_id": "KR_GOVT_5Y",
        "krx_kind": "국고채5년",
        "country": "KR",
        "name": "Korea Treasury Bond 5-Year Yield",
        "frequency": "D",
        "tenor": "5Y",
        "unit": "percent",
    },
    {
        "series_id": "KR_GOVT_10Y_DAILY",
        "krx_kind": "국고채10년",
        "country": "KR",
        "name": "Korea Treasury Bond 10-Year Yield",
        "frequency": "D",
        "tenor": "10Y",
        "unit": "percent",
    },
]
YAHOO_COMMODITY_SERIES = [
    {
        "series_id": "GOLD_USD_OZ",
        "symbol": "GC=F",
        "name": "Gold Futures",
        "commodity": "gold",
        "unit": "troy_oz",
        "currency": "USD",
    },
    {
        "series_id": "SILVER_USD_OZ",
        "symbol": "SI=F",
        "name": "Silver Futures",
        "commodity": "silver",
        "unit": "troy_oz",
        "currency": "USD",
    },
    {
        "series_id": "WTI_USD_BBL",
        "symbol": "CL=F",
        "name": "WTI Crude Oil Futures",
        "commodity": "wti",
        "unit": "barrel",
        "currency": "USD",
    },
    {
        "series_id": "BRENT_USD_BBL",
        "symbol": "BZ=F",
        "name": "Brent Crude Oil Futures",
        "commodity": "brent",
        "unit": "barrel",
        "currency": "USD",
    },
]
YAHOO_FX_SERIES = [
    {
        "series_id": "USD_KRW",
        "symbol": "KRW=X",
        "base_currency": "USD",
        "quote_currency": "KRW",
    },
    {
        "series_id": "USD_JPY",
        "symbol": "JPY=X",
        "base_currency": "USD",
        "quote_currency": "JPY",
    },
    {
        "series_id": "EUR_KRW",
        "symbol": "EURKRW=X",
        "base_currency": "EUR",
        "quote_currency": "KRW",
    },
    {
        "series_id": "JPY_KRW",
        "symbol": "JPYKRW=X",
        "base_currency": "JPY",
        "quote_currency": "KRW",
    },
    {
        "series_id": "CNY_KRW",
        "symbol": "CNYKRW=X",
        "base_currency": "CNY",
        "quote_currency": "KRW",
    },
    {
        "series_id": "AUD_KRW",
        "symbol": "AUDKRW=X",
        "base_currency": "AUD",
        "quote_currency": "KRW",
    },
    {
        "series_id": "USD_VND",
        "symbol": "USDVND=X",
        "base_currency": "USD",
        "quote_currency": "VND",
    },
]
YAHOO_DERIVED_FX_SERIES = [
    {
        "series_id": "VND_KRW",
        "numerator_symbol": "KRW=X",
        "denominator_symbol": "USDVND=X",
        "base_currency": "VND",
        "quote_currency": "KRW",
    },
]
