ProxyPreserveHost On

RedirectMatch 302 ^/$ /admin/
RedirectMatch 302 ^/admin$ /admin/

ProxyPass /admin/ http://127.0.0.1:8400/
ProxyPassReverse /admin/ http://127.0.0.1:8400/

ProxyPass /api/ http://127.0.0.1:8400/api/
ProxyPassReverse /api/ http://127.0.0.1:8400/api/

ProxyPass /assets/ http://127.0.0.1:8400/assets/
ProxyPassReverse /assets/ http://127.0.0.1:8400/assets/

ProxyPass /docs/ http://127.0.0.1:8400/docs/
ProxyPassReverse /docs/ http://127.0.0.1:8400/docs/

ProxyPass /files http://127.0.0.1:8400/files
ProxyPassReverse /files http://127.0.0.1:8400/files
